#!/bin/bash

CYPHER="./lgraph_cypher -u admin -P 73@TuGraph -p 7090 -f "
QUERY_DIR="./query"

cat $QUERY_DIR/q1.cypher
$CYPHER $QUERY_DIR/q1.cypher
echo

cat $QUERY_DIR/q2.cypher
$CYPHER $QUERY_DIR/q2.cypher
echo

cat $QUERY_DIR/q3.cypher
$CYPHER $QUERY_DIR/q3.cypher
echo

cat $QUERY_DIR/q4.cypher
$CYPHER $QUERY_DIR/q4.cypher
echo

cat $QUERY_DIR/q5.cypher
$CYPHER $QUERY_DIR/q5.cypher
echo

echo "QUERY DONE."